#ifndef DIRECTORYVIEW_CONSTANTS_H
#define DIRECTORYVIEW_CONSTANTS_H

namespace DirectoryViewPlugin
{

int GRID_HORIZONTAL_SPACE = 20;
int GRID_VERTICAL_SPACE = 20;
int GRID_LEFT_MARGIN = 10;
int GRID_RIGHT_MARGIN = 10;
int GRID_TOP_MARGIN = 10;
int GRID_BOTTOM_MARGIN = 10;

} // namespace DirectoryViewPlugin

#endif // DIRECTORYVIEW_CONSTANTS_H
