#ifndef DIRECTORYVIEW_GLOBAL_H
#define DIRECTORYVIEW_GLOBAL_H

#include <QtGlobal>

#if defined(DIRECTORYVIEW_LIBRARY)
#  define DIRECTORYVIEWSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIRECTORYVIEWSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIRECTORYVIEW_GLOBAL_H

