#ifndef NETWORKLOCATIONS_GLOBAL_H
#define NETWORKLOCATIONS_GLOBAL_H

#include <QtGlobal>

#if defined(NETWORKLOCATIONS_LIBRARY)
#  define NETWORKLOCATIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKLOCATIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKLOCATIONS_GLOBAL_H

