#ifndef SEARCHLOCATION_GLOBAL_H
#define SEARCHLOCATION_GLOBAL_H

#include <QtGlobal>

#if defined(SEARCHLOCATION_LIBRARY)
#  define SEARCHLOCATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEARCHLOCATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCHLOCATION_GLOBAL_H

