#ifndef DIRECTORYLISTVIEWWIDGET_GLOBAL_H
#define DIRECTORYLISTVIEWWIDGET_GLOBAL_H

#include <QtGlobal>

#if defined(DIRECTORYLISTVIEWWIDGET_LIBRARY)
#  define DIRECTORYLISTVIEWWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DIRECTORYLISTVIEWWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DIRECTORYLISTVIEWWIDGET_GLOBAL_H

